 # py code beginning 
 
# py code beginning

"""ReAct agent for mapping confirmed CDC report requirements to FHIR.

The agent receives the confirmed CDC reporting requirement
produced by Page 3 and investigates how those requirements
can be represented by existing FHIR artifacts.

Responsibilities:
- Search FHIR artifacts stored in HTKD.
- Search FHIR StructureDefinition elements.
- Inspect exact FHIR elements.
- Retrieve authoritative FHIR evidence.
- Produce structured CDC-to-FHIR mapping results.

The agent does NOT:
- Create database engines.
- Import FHIR packages.
- Modify HTKD.
- Create FSH.
- Decide the final CDC IG design.
- Automatically create Profiles, Extensions,
  ValueSets, or CodeSystems.

IG design decisions belong to the later Gap / ReAct stage.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from pydantic_ai import Agent, RunContext

from sqlalchemy.engine import Engine

from htkd.db.fhir_db import (
    get_fhir_element,
    get_fhir_evidence,
    get_fhir_package_dependencies,
    get_fhir_packages,
    search_fhir_artifacts,
    search_fhir_elements,
)

from models.htkd_cdc_fhir_ig_models import (
    CDCFHIRMappingResult,
    CDCReportRequirement,
)

from nri_ai_core.ai_runtime import (
    build_agent_model,
)


# =========================================
# CONSTANTS
# =========================================

DEFAULT_SEARCH_LIMIT = 10


# =========================================
# DEPENDENCIES
# =========================================

@dataclass
class HTKDCdcFHIRMappingDeps:
    """Runtime dependencies and observations.

    The confirmed CDC requirement is supplied through
    the prompt.

    Dependencies contain runtime resources and the
    evidence generated by tool calls.
    """

    engine: Engine

    fhir_tool_called: bool = False

    fhir_tool_call_count: int = 0

    fhir_observation_count: int = 0

    fhir_evidence: list[
        dict[str, Any]
    ] = field(
        default_factory=list
    )


# =========================================
# INTERNAL HELPERS
# =========================================

def _record_observation(
    *,
    deps: HTKDCdcFHIRMappingDeps,
    tool_name: str,
    arguments: dict[str, Any],
    observation: Any,
) -> None:
    """Record one operational ReAct observation."""

    deps.fhir_tool_called = True

    deps.fhir_tool_call_count += 1
    deps.fhir_observation_count += 1

    deps.fhir_evidence.append(
        {
            "tool": tool_name,
            "arguments": arguments,
            "observation": observation,
        }
    )


def _normalize_limit(
    limit: int,
) -> int:
    """Keep agent tool search limits small."""

    try:
        value = int(limit)
    except (TypeError, ValueError):
        value = DEFAULT_SEARCH_LIMIT

    return max(
        1,
        min(
            value,
            20,
        ),
    )


# =========================================
# AGENT FACTORY
# =========================================

def create_htkd_cdc_fhir_mapping_agent(
    llm_cfg: dict,
) -> Agent[
    HTKDCdcFHIRMappingDeps,
    CDCFHIRMappingResult,
]:
    """Create the CDC FHIR mapping ReAct agent."""

    model = build_agent_model(
        llm_cfg
    )

    agent = Agent(
        model,
        deps_type=HTKDCdcFHIRMappingDeps,
        output_type=CDCFHIRMappingResult,
        instructions=(
            """
You are the HTKD CDC FHIR Mapping Agent.

Your task is to investigate how confirmed CDC reporting
requirements can be represented using existing FHIR
artifacts.

The confirmed CDC requirement is authoritative for the
business reporting requirement.

HTKD FHIR evidence is authoritative for what the currently
loaded FHIR packages provide.


FHIR PACKAGE DISCOVERY
----------------------

FHIR package discovery is the mandatory first ReAct action
for every new mapping run.

Before searching for or inspecting any package-specific
FHIR artifact, you MUST call list_fhir_packages.

Treat the returned package list as an observation from
HTKD.

Do not assume from model knowledge which FHIR packages are
installed, relevant, or available.

After observing the available packages:

- Reason about which available implementation guides may
  be relevant to the confirmed CDC reporting requirements.

- When a specialized implementation guide may be relevant,
  call inspect_package_dependencies before making a final
  mapping conclusion from that package.

- Use the returned dependency information to understand
  relationships between specialized IGs, base IGs, and
  FHIR Core.

- For each CDC field or component, decide from the
  observations which package evidence should be
  investigated next.

- Prefer the most specific relevant evidence actually found
  in HTKD, while inspecting inherited or base-package
  evidence when necessary.

- Do not conclude Covered, Partial, or Missing from FHIR
  Core evidence alone when a more specific relevant
  implementation guide is available but has not yet been
  reasonably investigated.

- Do not assume that NIDRS, TW Core, TWIDIR, or any other
  package is available or applicable until the tool
  observations support that conclusion.

- Do not treat a CI build as an authorized published
  implementation guide.

- Preserve publication status, maturity status, package
  name, and package version when this information is
  relevant to the analysis.

- When a specialized profile derives from a base profile,
  preserve evidence for the specialized profile and use
  base-package evidence where needed to understand
  inherited structure.

Package metadata and package dependencies are evidence for
planning the investigation.

They are not, by themselves, evidence that a particular
CDC requirement is Covered.


FHIR REACT PROCESS
------------------

You must use the available FHIR tools when making FHIR
mapping claims.

This is an evidence-grounded ReAct task:

1. Read the confirmed CDC reporting requirement.

2. Call list_fhir_packages and observe the FHIR knowledge
   sources actually available in HTKD.

3. Reason about which available package or packages are
   relevant to this reporting problem.

4. Inspect package dependencies when a relevant specialized
   implementation guide is available.

5. For each reportable field or component, reason about
   what FHIR resource, profile, or element may represent
   the requirement and which available package should be
   investigated.

6. Use the tools to search for candidate FHIR artifacts
   and elements.

7. Inspect exact candidate elements before claiming that
   a mapping is supported.

8. Retrieve FHIR evidence when terminology bindings or
   related ValueSets and CodeSystems are relevant.

9. Reconsider the mapping using the returned observations.

   If the observation is insufficient, choose another
   appropriate tool action.

Before finalizing Needs Investigation for a reportable
field or component:

- Do not use Needs Investigation merely because the first
  search did not return sufficient evidence.

- If a plausible FHIR resource, profile, or element has
  been identified but exact evidence has not yet been
  inspected, continue the ReAct investigation.

- When an artifact search identifies a plausible resource
  or profile, use element search when needed to locate the
  relevant element.

- When an element search identifies a plausible element,
  inspect the exact element before finalizing the mapping.

- If a relevant specialized package does not provide
  sufficient evidence, investigate an appropriate
  dependency or base package when that may resolve the
  requirement.

- An empty tool result is an observation. Use it to decide
  the next reasonable action rather than treating it as
  proof that the requirement is Missing.

- Use Needs Investigation only after reasonable available
  tool actions have been attempted and the evidence
  remains insufficient.

10. Produce the structured mapping result only after the
    evidence investigation is sufficient.

Do not expose private chain-of-thought.

Tool calls and retrieved evidence provide the operational
ReAct trace.


EVIDENCE RULES
--------------

- Preserve the original CDC section names, field names,
  and component names.

- Do not translate the CDC source requirement into ICD,
  SNOMED CT, LOINC, or another terminology unless the
  FHIR evidence actually requires terminology analysis.

- Do not invent FHIR element paths.

- Do not claim an element exists without tool evidence.

- Do not claim a ValueSet or CodeSystem is locally
  available unless the retrieved evidence supports it.

- A FHIR CodeSystem may reference an external terminology
  without containing that terminology locally.

- One CDC field may map to more than one FHIR element.

- Multiple CDC fields may belong to the same FHIR
  resource.

- Composite CDC fields must be considered at component
  level when their components represent different data.

- Package discovery does not mean that every available
  package must be used for every requirement.

- Package relevance must be determined from the reporting
  requirement and actual HTKD observations.

- A package must not appear in packages_consulted merely
  because list_fhir_packages returned it.

- packages_consulted must contain only packages that were
  actually investigated through package-specific tool
  evidence.


MAPPING STATUS
--------------

Use only these mapping statuses:

Covered
Partial
Missing
Needs Investigation


Covered:

Existing inspected FHIR evidence can represent the
confirmed requirement without an identified structural
gap.


Partial:

Existing FHIR evidence represents part of the requirement,
but some confirmed meaning, constraint, component, or
terminology requirement is not fully represented by the
inspected evidence.


Missing:

The investigation found no suitable representation in the
currently inspected and available FHIR evidence.

Before using Missing, make a reasonable investigation of
relevant specialized implementation guides that were
discovered in HTKD.

Do not classify a requirement as Missing merely because
FHIR Core does not contain a suitable representation when
a relevant specialized IG remains uninvestigated.


Needs Investigation:

The available evidence is insufficient to make a supported
Covered, Partial, or Missing determination.


PAGE 4 BOUNDARY
---------------

This stage performs evidence-grounded mapping against
existing FHIR knowledge.

Do NOT decide in this stage to create:

- a new CDC Profile
- an Extension
- a new ValueSet
- a new CodeSystem
- FSH

Those are design decisions for the later Gap / ReAct
stage.


OUTPUT RULES
------------

packages_consulted must contain only packages that were
actually investigated through tool evidence.

mapping_explanation must be concise and evidence based.

unresolved_questions should contain only issues that
remain unresolved after reasonable tool investigation.
"""
        ),
    )

    # =====================================
    # TOOL 0A — LIST FHIR PACKAGES
    # =====================================

    @agent.tool
    def list_fhir_packages(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
    ) -> list[dict[str, Any]]:
        """List FHIR packages currently available in HTKD.

        Use this before assuming which FHIR implementation
        guides or package versions are locally available.
        """

        rows = get_fhir_packages(
            engine=ctx.deps.engine,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name="list_fhir_packages",
            arguments={},
            observation=rows,
        )

        return rows

    # =====================================
    # TOOL 0B — PACKAGE DEPENDENCIES
    # =====================================

    @agent.tool
    def inspect_package_dependencies(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
        package_name: str,
        package_version: str | None = None,
    ) -> list[dict[str, Any]]:
        """Inspect declared dependencies of a FHIR package.

        Use this to understand the relationship between
        locally available FHIR packages and implementation
        guides.
        """

        rows = get_fhir_package_dependencies(
            engine=ctx.deps.engine,
            package_name=package_name,
            package_version=package_version,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name=(
                "inspect_package_dependencies"
            ),
            arguments={
                "package_name": package_name,
                "package_version": (
                    package_version
                ),
            },
            observation=rows,
        )

        return rows

    # =====================================
    # TOOL 1 — SEARCH FHIR ARTIFACTS
    # =====================================

    @agent.tool
    def search_fhir(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
        query: str,
        resource_type: str | None = None,
        package_name: str | None = None,
        limit: int = DEFAULT_SEARCH_LIMIT,
    ) -> list[dict[str, Any]]:
        """Search FHIR artifacts available in HTKD.

        Use this to discover candidate resources,
        StructureDefinitions, ValueSets, or CodeSystems.
        """

        normalized_limit = (
            _normalize_limit(
                limit
            )
        )

        rows = search_fhir_artifacts(
            engine=ctx.deps.engine,
            query=query,
            package_name=package_name,
            resource_type=resource_type,
            limit=normalized_limit,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name="search_fhir",
            arguments={
                "query": query,
                "resource_type": (
                    resource_type
                ),
                "package_name": (
                    package_name
                ),
                "limit": normalized_limit,
            },
            observation=rows,
        )

        return rows

    # =====================================
    # TOOL 2 — SEARCH FHIR ELEMENTS
    # =====================================

    @agent.tool
    def search_element(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
        query: str,
        resource_name: str | None = None,
        package_name: str | None = None,
        limit: int = DEFAULT_SEARCH_LIMIT,
    ) -> list[dict[str, Any]]:
        """Search StructureDefinition elements.

        Use this when the exact FHIR element path is not
        yet known.
        """

        normalized_limit = (
            _normalize_limit(
                limit
            )
        )

        rows = search_fhir_elements(
            engine=ctx.deps.engine,
            query=query,
            resource_name=resource_name,
            package_name=package_name,
            limit=normalized_limit,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name="search_element",
            arguments={
                "query": query,
                "resource_name": (
                    resource_name
                ),
                "package_name": (
                    package_name
                ),
                "limit": normalized_limit,
            },
            observation=rows,
        )

        return rows

    # =====================================
    # TOOL 3 — INSPECT EXACT ELEMENT
    # =====================================

    @agent.tool
    def inspect_element(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
        path: str,
        artifact_id: str | None = None,
        package_name: str | None = None,
    ) -> list[dict[str, Any]]:
        """Inspect an exact FHIR element path.

        Use this before claiming that a candidate element
        supports a CDC reporting requirement.
        """

        rows = get_fhir_element(
            engine=ctx.deps.engine,
            path=path,
            package_name=package_name,
            artifact_id=artifact_id,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name="inspect_element",
            arguments={
                "path": path,
                "artifact_id": (
                    artifact_id
                ),
                "package_name": (
                    package_name
                ),
            },
            observation=rows,
        )

        return rows

    # =====================================
    # TOOL 4 — INSPECT FHIR EVIDENCE
    # =====================================

    @agent.tool
    def inspect_fhir_evidence(
        ctx: RunContext[
            HTKDCdcFHIRMappingDeps
        ],
        element_path: str,
        package_name: str | None = None,
    ) -> dict[str, Any]:
        """Retrieve related evidence for a FHIR element.

        This may include:
        - exact element definitions
        - terminology binding
        - bound ValueSet
        - ValueSet compose rules
        - referenced CodeSystem metadata
        """

        evidence = get_fhir_evidence(
            engine=ctx.deps.engine,
            element_path=element_path,
            package_name=package_name,
        )

        _record_observation(
            deps=ctx.deps,
            tool_name=(
                "inspect_fhir_evidence"
            ),
            arguments={
                "element_path": (
                    element_path
                ),
                "package_name": (
                    package_name
                ),
            },
            observation=evidence,
        )

        return evidence

    return agent


# =========================================
# PROMPT BUILDER
# =========================================

def build_cdc_fhir_mapping_prompt(
    requirement: CDCReportRequirement,
) -> str:
    """Build the Page 4 mapping prompt."""

    requirement_json = (
        requirement.model_dump_json(
            indent=2
        )
    )

    return f"""
Analyze the following confirmed CDC reporting requirement.

This JSON is the human-confirmed output from the previous
workflow stage. Treat it as the business requirement input.

Investigate how every reportable field and relevant
component can be represented using the FHIR evidence
available through your tools.

Do not perform IG design yet.

Confirmed CDC Reporting Requirement:

{requirement_json}
""".strip()


# =========================================
# PUBLIC RUNNER
# =========================================

def map_cdc_report_to_fhir(
    *,
    requirement: CDCReportRequirement,
    engine: Engine,
    llm_cfg: dict,
) -> tuple[
    CDCFHIRMappingResult,
    HTKDCdcFHIRMappingDeps,
]:
    """Run the Page 4 CDC-to-FHIR ReAct mapping."""

    agent = (
        create_htkd_cdc_fhir_mapping_agent(
            llm_cfg
        )
    )

    deps = HTKDCdcFHIRMappingDeps(
        engine=engine
    )

    prompt = (
        build_cdc_fhir_mapping_prompt(
            requirement
        )
    )

    result = agent.run_sync(
        prompt,
        deps=deps,
    )

    return (
        result.output,
        deps,
    )

